//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace harpersPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDrinks = new HashSet<OrderDrink>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime Time { get; set; }
        public int EventID { get; set; }
        public bool PreOrder { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> TabID { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDrink> OrderDrinks { get; set; }
        public virtual Tab Tab { get; set; }
    }
}
