//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace harpersPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int TabID { get; set; }
        public int EventID { get; set; }
        public short TableNumber { get; set; }
        public bool Open { get; set; }
        public Nullable<decimal> PriceLimit { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
